<?php
/**
 * @file
 * provides the secureshare implementation as a block
 */

/**
 * Implementation of hook_block_info()
 * provides a Socialshare privacy as block
 *
 * @return array
 */
function secureshare_blocks_block_info() {
  $blocks = array();

  $blocks['default'] = array(
    'info' => t('Socialshare privacy'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implementation of hook_block_configure()
 * provides block settings for Socialshare privacy.
 *
 * @param string $delta
 * @return array
 */
function secureshare_blocks_block_configure($delta = '') {
  $form = array();

  $options = array();
  ctools_include('export');
  foreach (ctools_export_crud_load_all('secureshare_profiles') as $profile) {
    if (empty($profile->disabled)) {
      $options[$profile->name] = $profile->name;
    }
  }

  $form['secureshare_profile'] = array(
    '#type' => 'select',
    '#title' => t('Secureshare settings profile'),
    '#empty_value' => '',
    '#default_value' => variable_get('secureshare_blocks_' . $delta, 'default'),
    '#options' => ($options) ? $options : array(),
  );

  return $form;
}

/**
 * Implementation of hook_block_save()
 *
 * @param string $delta
 * @param array $edit
 */
function secureshare_blocks_block_save($delta = '', $edit = array()) {
  variable_set('secureshare_blocks_' . $delta, $edit['secureshare_profile']);
}

/**
 * Implementation of hook_block_view
 *
 * @param string $delta
 * @return array
 */
function secureshare_blocks_block_view($delta = '') {
  if (function_exists($function = 'secureshare_blocks_block_' . $delta . '_view')) {
    return $function();
  }
}

/**
 * Implementation of hook_block_view > delta > default
 *
 * @return array
 *  returns the block elements as render elements
 */
function secureshare_blocks_block_default_view() {
  $output = array();
  $profile = variable_get('secureshare_blocks_default', 'default');

  if (!empty($profile)) {
    return array(
      'subject' => t('Secureshare'),
      'content' => array(
        'secureshare' => array(
          '#type' => 'secureshare',
          '#secureshare_profile' => $profile,
        ),
      ),
    );
  }

  return $output;
}