<?php

/**
 * Implements hook_field_extra_fields().
 */
function secureshare_fields_field_extra_fields() {
  $extra = array();
  ctools_include('export');

  foreach (field_info_bundles() as $entity => $bundles) {
    foreach (array_keys($bundles) as $bundle) {
      $profile = ctools_export_crud_load('secureshare_profiles', variable_get("secureshare_fields_{$entity}_{$bundle}", NULL));

      if (!empty($profile)) {
        $extra[$entity][$bundle] = array(
          'display' => array(
            'secureshare' => array(
              'label' => t('Secureshare socialprivacy'),
              'description' => t('Secureshare Socialprivacy'),
              'weight' => 100,
            ),
          ),
        );
      }
    }
  }

  return $extra;
}

function secureshare_fields_entity_view($entity, $type, $view_mode, $langcode) {
  ctools_include('export');

  if(isset($entity->content['#bundle']) && $entity->content['#bundle']) {
    $profile = ctools_export_crud_load('secureshare_profiles', variable_get("secureshare_fields_{$type}_{$entity->content['#bundle']}", NULL));

    if (!empty($profile)) {
      $entity->content['secureshare'] = array(
        '#type' => 'secureshare',
        '#secureshare_profile' => $profile->name,
        '#weight' => 100,
      );
    }
  }
}


function secureshare_fields_form_alter(&$form, &$form_state, $form_id) {
  ctools_include('export');

  if ($form_id == 'node_type_form') {
    $form['secureshare'] = array(
      '#type' => 'fieldset',
      '#title' => t('Secureshare profile'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#group' => 'additional_settings',
    );

    $options = array();
    ctools_include('export');
    foreach (ctools_export_crud_load_all('secureshare_profiles') as $profile) {
      if (empty($profile->disabled)) {
        $options[$profile->name] = $profile->name;
      }
    }

    $form['secureshare']['secureshare_fields_node'] = array(
      '#type' => 'select',
      '#title' => t('Profile'),
      '#empty_value' => '',
      '#options' => $options,
      '#default_value' => variable_get("secureshare_fields_node_{$form['#node_type']->type}", ''),
    );

    $form['#submit'][] = 'secureshare_fields_node_type_form_submit';
  }
}

function secureshare_fields_node_type_form_submit($form, &$form_state) {
  field_cache_clear();
}