<?php
/**
 * @file
 * Interface to provide an easy and quick way of translating vocabulary terms.
 */

/**
 * Implements hook_menu().
 */
function translateterms_menu() {
  $items['admin/structure/taxonomy/%taxonomy_vocabulary_machine_name/translate_terms'] = array(
    'title' => 'Translate Terms',
    'description' => 'Provides a quick and easy way of translating vocabulary terms.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('translateterms_admin', 3),
    'access callback' => 'i18n_taxonomy_vocabulary_translation_tab_sets_access',
    'access arguments' => array(3),
    'type' => MENU_LOCAL_TASK,
    'file' => 'translateterms.admin.inc',
    'weight' => 10,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function translateterms_theme($existing, $type, $theme, $path) {
  return array(
    'translateterms_terms' => array(
      'render element' => 'form',
      'file' => 'translateterms.admin.inc',
    ),
  );
}

/**
 * Implements hook i18n_object_info().
 */
function translateterms_i18n_object_info() {
  $info['taxonomy_vocabulary']['translateterms path'] = 'admin/structure/taxonomy/%taxonomy_vocabulary_machine_name/translate_terms';
}
