<?php

/**
 * @file
 * Provides administration enhancements, based on Radix theme
 */

/**
 * Implements hook_navbar_view_alter().
 */
function radix_admin_navbar_view_alter(&$links) {

  // provide some default icons to navbar
  $icons = array(
    'navbar_navigation' => array(
      'home' => 'home',
      'navbar_tray_toggle' => 'reorder',
    ),
    'navbar_user' => array(
      'account' => 'user',
      'login' => 'signin',
      'logout' => 'signout',
    ),
  );

  $icons['navbar_menu'] = array(
    'admin/apps' => 'th-large',
    'admin/content' => 'file',
    'admin/panopoly' => 'magic',
    'admin/structure' => 'sitemap',
    'admin/appearance' => 'eye-open',
    'admin/people' => 'group',
    'admin/modules' => 'th-list',
    'admin/config' => 'cog',
    'admin/reports' => 'list-alt',
  );

  foreach (element_children($links) as $name) {
    if (isset($icons[$name])) {
      if ($name == 'navbar_menu') {
        foreach (element_children($links[$name]) as $key) {
          $link = $links[$name][$key];
          $icon = isset($icons[$name][$link['#href']]) ? $icons[$name][$link['#href']] : 'circle-arrow-right'; // default icon
          $title = '<span>' . $link['#title'] . '</span>';
          $icon = '<i class="icon-' . $icon . '"></i>';
          $links[$name][$key]['#title'] = $icon . $title;
          $links[$name][$key]['#localized_options']['html'] = TRUE;
        }
      } else {
        foreach ($links[$name]['#links'] as $key => $link) {
          if (isset($icons[$name][$key])) {
            $title = '<span>' . $links[$name]['#links'][$key]['title'] . '</span>';
            $icon = '<i class="icon-' . $icons[$name][$key] . '"></i>';
            $links[$name]['#links'][$key]['title'] = $icon . $title;
            $links[$name]['#links'][$key]['html'] = TRUE;
          }
        }
      }
    }
  }
}